<?php

namespace go1\util;

class Languages
{
    const ALL = [
        'af'          => ['Afrikaans', 'Afrikaans'],
        'am'          => ['Amharic', 'አማርኛ'],
        'ar'          => ['Arabic', 'العربية', true],
        'ast'         => ['Asturian', 'Asturianu'],
        'az'          => ['Azerbaijani', 'Azərbaycanca'],
        'be'          => ['Belarusian', 'Беларуская'],
        'bg'          => ['Bulgarian', 'Български'],
        'bn'          => ['Bengali', 'বাংলা'],
        'bo'          => ['Tibetan', 'བོད་སྐད་'],
        'bs'          => ['Bosnian', 'Bosanski'],
        'ca'          => ['Catalan', 'Català'],
        'cs'          => ['Czech', 'Čeština'],
        'cy'          => ['Welsh', 'Cymraeg'],
        'da'          => ['Danish', 'Dansk'],
        'de'          => ['German', 'Deutsch'],
        'dz'          => ['Dzongkha', 'རྫོང་ཁ'],
        'el'          => ['Greek', 'Ελληνικά'],
        'en'          => ['English', 'English'],
        'en-au'       => ['English (AU)', 'English'],
        'en-uk'       => ['English (UK)', 'English'],
        'en-us'       => ['English (US)', 'English'],
        'en-x-simple' => ['Simple English', 'Simple English'],
        'eo'          => ['Esperanto', 'Esperanto'],
        'es'          => ['Spanish', 'Español'],
        'et'          => ['Estonian', 'Eesti'],
        'eu'          => ['Basque', 'Euskera'],
        'fa'          => ['Persian, Farsi', 'فارسی', true],
        'fi'          => ['Finnish', 'Suomi'],
        'fil'         => ['Filipino', 'Filipino'],
        'fo'          => ['Faeroese', 'Føroyskt'],
        'fr'          => ['French', 'Français'],
        'fy'          => ['Frisian, Western', 'Frysk'],
        'ga'          => ['Irish', 'Gaeilge'],
        'gd'          => ['Scots Gaelic', 'Gàidhlig'],
        'gl'          => ['Galician', 'Galego'],
        'gsw-berne'   => ['Swiss German', 'Schwyzerdütsch'],
        'gu'          => ['Gujarati', 'ગુજરાતી'],
        'he'          => ['Hebrew', 'עברית', true],
        'hi'          => ['Hindi', 'हिन्दी'],
        'hr'          => ['Croatian', 'Hrvatski'],
        'ht'          => ['Haitian Creole', 'Kreyòl ayisyen'],
        'hu'          => ['Hungarian', 'Magyar'],
        'hy'          => ['Armenian', 'Հայերեն'],
        'id'          => ['Indonesian', 'Bahasa Indonesia'],
        'is'          => ['Icelandic', 'Íslenska'],
        'it'          => ['Italian', 'Italiano'],
        'ja'          => ['Japanese', '日本語'],
        'jv'          => ['Javanese', 'Basa Java'],
        'ka'          => ['Georgian', 'ქართული ენა'],
        'kk'          => ['Kazakh', 'Қазақ'],
        'km'          => ['Khmer', 'ភាសាខ្មែរ'],
        'kn'          => ['Kannada', 'ಕನ್ನಡ'],
        'ko'          => ['Korean', '한국어'],
        'ku'          => ['Kurdish', 'Kurdî'],
        'ky'          => ['Kyrgyz', 'Кыргызча'],
        'lo'          => ['Lao', 'ພາສາລາວ'],
        'lt'          => ['Lithuanian', 'Lietuvių'],
        'lv'          => ['Latvian', 'Latviešu'],
        'mg'          => ['Malagasy', 'Malagasy'],
        'mk'          => ['Macedonian', 'Македонски'],
        'ml'          => ['Malayalam', 'മലയാളം'],
        'mn'          => ['Mongolian', 'монгол'],
        'mr'          => ['Marathi', 'मराठी'],
        'ms'          => ['Bahasa Malaysia', 'بهاس ملايو'],
        'my'          => ['Burmese', 'ဗမာစကား'],
        'ne'          => ['Nepali', 'नेपाली'],
        'nl'          => ['Dutch', 'Nederlands'],
        'nb'          => ['Norwegian Bokmål', 'Norsk, bokmål'],
        'nn'          => ['Norwegian Nynorsk', 'Norsk, nynorsk'],
        'oc'          => ['Occitan', 'Occitan'],
        'pa'          => ['Punjabi', 'ਪੰਜਾਬੀ'],
        'pl'          => ['Polish', 'Polski'],
        'pt-pt'       => ['Portuguese, Portugal', 'Português, Portugal'],
        'pt-br'       => ['Portuguese, Brazil', 'Português, Brasil'],
        'ro'          => ['Romanian', 'Română'],
        'ru'          => ['Russian', 'Русский'],
        'sco'         => ['Scots', 'Scots'],
        'se'          => ['Northern Sami', 'Sámi'],
        'si'          => ['Sinhala', 'සිංහල'],
        'sk'          => ['Slovak', 'Slovenčina'],
        'sl'          => ['Slovenian', 'Slovenščina'],
        'sq'          => ['Albanian', 'Shqip'],
        'sr'          => ['Serbian', 'Српски'],
        'sv'          => ['Swedish', 'Svenska'],
        'sw'          => ['Swahili', 'Kiswahili'],
        'ta'          => ['Tamil', 'தமிழ்'],
        'ta-lk'       => ['Tamil, Sri Lanka', 'தமிழ், இலங்கை'],
        'te'          => ['Telugu', 'తెలుగు'],
        'th'          => ['Thai', 'ภาษาไทย'],
        'tr'          => ['Turkish', 'Türkçe'],
        'tyv'         => ['Tuvan', 'Тыва дыл'],
        'ug'          => ['Uyghur', 'ئۇيغۇرچە', true],
        'uk'          => ['Ukrainian', 'Українська'],
        'ur'          => ['Urdu', 'اردو', true],
        'vi'          => ['Vietnamese', 'Tiếng Việt'],
        'xx-lolspeak' => ['Lolspeak', 'Lolspeak'],
        'zh-hans'     => ['Chinese, Simplified', '简体中文'],
        'zh-hant'     => ['Chinese, Traditional', '繁體中文'],
        'af-za'       => ['Afrikaans', 'Afrikaans'],
        'sq-al'       => ['Albanian', 'Shqip'],
        'ar-dz'       => ['Arabic (Algeria)', 'العربية (الجزائر)', true],
        'ar-bh'       => ['Arabic (Bahrain)', 'العربية (البحرين)', true],
        'ar-eg'       => ['Arabic (Egypt)', 'العربية (مصر)', true],
        'ar-iq'       => ['Arabic (Iraq)', 'العربية (العراق)', true],
        'ar-jo'       => ['Arabic (Jordan)', 'العربية (الأردن)', true],
        'ar-kw'       => ['Arabic (Kuwait)', 'العربية (الكويت)', true],
        'ar-lb'       => ['Arabic (Lebanon)', 'العربية (لبنان)', true],
        'ar-ly'       => ['Arabic (Libya)', 'العربية (ليبيا)', true],
        'ar-ma'       => ['Arabic (Morocco)', 'العربية (المغرب)', true],
        'ar-om'       => ['Arabic (Oman)', 'العربية (عمان)', true],
        'ar-qa'       => ['Arabic (Qatar)', 'العربية (قطر)', true],
        'ar-sa'       => ['Arabic (Saudi Arabia)', 'العربية (السعودية)', true],
        'ar-sy'       => ['Arabic (Syria)', 'العربية (سوريا)', true],
        'ar-tn'       => ['Arabic (Tunisia)', 'العربية (تونس)', true],
        'ar-ae'       => ['Arabic (United Arab Emirates)', 'العربية (الإمارات العربية المتحدة)', true],
        'ar-ye'       => ['Arabic (Yemen)', 'العربية (اليمن)', true],
        'hy-am'       => ['Armenian', 'Հայերեն'],
        'az-az'       => ['Azerbaijani', 'Azərbaycanca'],
        'eu-es'       => ['Basque', 'Euskara'],
        'be-by'       => ['Belarusian', 'Беларуская'],
        'bn-bd'       => ['Bengali (Bangladesh)', 'বাংলা (বাংলাদেশ)'],
        'bn-in'       => ['Bengali (India)', 'বাংলা (ভারত)'],
        'bs-ba'       => ['Bosnian', 'Bosanski'],
        'bg-bg'       => ['Bulgarian', 'Български'],
        'ca-es'       => ['Catalan', 'Català'],
        'zh-cn'       => ['Chinese (Simplified)', '中文 (简体)'],
        'zh-hk'       => ['Chinese (Hong Kong)', '中文 (香港)'],
        'zh-tw'       => ['Chinese (Traditional)', '中文 (繁體)'],
        'hr-hr'       => ['Croatian', 'Hrvatski'],
        'cs-cz'       => ['Czech', 'Čeština'],
        'da-dk'       => ['Danish', 'Dansk'],
        'nl-be'       => ['Dutch (Belgium)', 'Nederlands (België)'],
        'nl-nl'       => ['Dutch (Netherlands)', 'Nederlands (Nederland)'],
        'en-ca'       => ['English (Canada)', 'English (Canada)'],
        'en-in'       => ['English (India)', 'English (India)'],
        'en-ie'       => ['English (Ireland)', 'English (Ireland)'],
        'en-mt'       => ['English (Malta)', 'English (Malta)'],
        'en-nz'       => ['English (New Zealand)', 'English (New Zealand)'],
        'en-ph'       => ['English (Philippines)', 'English (Philippines)'],
        'en-sg'       => ['English (Singapore)', 'English (Singapore)'],
        'en-za'       => ['English (South Africa)', 'English (South Africa)'],
        'en-gb'       => ['English (United Kingdom)', 'English (United Kingdom)'],
        'et-ee'       => ['Estonian', 'Eesti'],
        'fi-fi'       => ['Finnish', 'Suomi'],
        'fr-be'       => ['French (Belgium)', 'Français (Belgique)'],
        'fr-ca'       => ['French (Canada)', 'Français (Canada)'],
        'fr-fr'       => ['French (France)', 'Français (France)'],
        'fr-lu'       => ['French (Luxembourg)', 'Français (Luxembourg)'],
        'fr-ch'       => ['French (Switzerland)', 'Français (Suisse)'],
        'gl-es'       => ['Galician', 'Galego'],
        'ka-ge'       => ['Georgian', 'ქართული'],
        'de-at'       => ['German (Austria)', 'Deutsch (Österreich)'],
        'de-de'       => ['German (Germany)', 'Deutsch (Deutschland)'],
        'de-lu'       => ['German (Luxembourg)', 'Deutsch (Luxemburg)'],
        'de-ch'       => ['German (Switzerland)', 'Deutsch (Schweiz)'],
        'el-cy'       => ['Greek (Cyprus)', 'Ελληνικά (Κύπρος)'],
        'el-gr'       => ['Greek (Greece)', 'Ελληνικά (Ελλάδα)'],
        'gu-in'       => ['Gujarati', 'ગુજરાતી'],
        'he-il'       => ['Hebrew', 'עברית', true],
        'hi-in'       => ['Hindi', 'हिन्दी'],
        'hu-hu'       => ['Hungarian', 'Magyar'],
        'is-is'       => ['Icelandic', 'Íslenska'],
        'id-id'       => ['Indonesian', 'Bahasa Indonesia'],
        'it-it'       => ['Italian', 'Italiano'],
        'it-ch'       => ['Italian (Switzerland)', 'Italiano (Svizzera)'],
        'ja-jp'       => ['Japanese', '日本語'],
        'kn-in'       => ['Kannada', 'ಕನ್ನಡ'],
        'kk-kz'       => ['Kazakh', 'Қазақша'],
        'ko-kr'       => ['Korean', '한국어'],
        'ky-kg'       => ['Kyrgyz', 'Кыргызча'],
        'lv-lv'       => ['Latvian', 'Latviešu'],
        'lt-lt'       => ['Lithuanian', 'Lietuvių'],
        'mk-mk'       => ['Macedonian', 'Македонски'],
        'ms-my'       => ['Malay', 'Bahasa Melayu'],
        'mr-in'       => ['Marathi', 'मराठी'],
        'mn-mn'       => ['Mongolian', 'Монгол'],
        'no-no'       => ['Norwegian', 'Norsk'],
        'fa-ir'       => ['Persian', 'فارسی', true],
        'pl-pl'       => ['Polish', 'Polski'],
        'pa-in'       => ['Punjabi', 'ਪੰਜਾਬੀ'],
        'ro-ro'       => ['Romanian', 'Română'],
        'ru-ru'       => ['Russian', 'Русский'],
        'sr-rs'       => ['Serbian', 'Српски'],
        'sk-sk'       => ['Slovak', 'Slovenčina'],
        'sl-si'       => ['Slovenian', 'Slovenščina'],
        'es-ar'       => ['Spanish (Argentina)', 'Español (Argentina)'],
        'es-bo'       => ['Spanish (Bolivia)', 'Español (Bolivia)'],
        'es-cl'       => ['Spanish (Chile)', 'Español (Chile)'],
        'es-co'       => ['Spanish (Colombia)', 'Español (Colombia)'],
        'es-cr'       => ['Spanish (Costa Rica)', 'Español (Costa Rica)'],
        'es-do'       => ['Spanish (Dominican Republic)', 'Español (República Dominicana)'],
        'es-ec'       => ['Spanish (Ecuador)', 'Español (Ecuador)'],
        'es-sv'       => ['Spanish (El Salvador)', 'Español (El Salvador)'],
        'es-gt'       => ['Spanish (Guatemala)', 'Español (Guatemala)'],
        'es-hn'       => ['Spanish (Honduras)', 'Español (Honduras)'],
        'es-mx'       => ['Spanish (Mexico)', 'Español (México)'],
        'es-ni'       => ['Spanish (Nicaragua)', 'Español (Nicaragua)'],
        'es-pa'       => ['Spanish (Panama)', 'Español (Panamá)'],
        'es-py'       => ['Spanish (Paraguay)', 'Español (Paraguay)'],
        'es-pe'       => ['Spanish (Peru)', 'Español (Perú)'],
        'es-pr'       => ['Spanish (Puerto Rico)', 'Español (Puerto Rico)'],
        'es-es'       => ['Spanish (Spain)', 'Español (España)'],
        'es-us'       => ['Spanish (United States)', 'Español (Estados Unidos)'],
        'es-uy'       => ['Spanish (Uruguay)', 'Español (Uruguay)'],
        'es-ve'       => ['Spanish (Venezuela)', 'Español (Venezuela)'],
        'sw-ke'       => ['Swahili (Kenya)', 'Kiswahili (Kenya)'],
        'sv-se'       => ['Swedish', 'Svenska'],
        'ta-in'       => ['Tamil', 'தமிழ்'],
        'te-in'       => ['Telugu', 'తెలుగు'],
        'th-th'       => ['Thai', 'ไทย'],
        'tr-tr'       => ['Turkish', 'Türkçe'],
        'uk-ua'       => ['Ukrainian', 'Українська'],
        'ur-pk'       => ['Urdu', 'اردو', true],
        'uz-uz'       => ['Uzbek', 'Oʻzbekcha'],
        'vi-vn'       => ['Vietnamese', 'Tiếng Việt'],
        'cy-gb'       => ['Welsh', 'Cymraeg']
    ];

    // last updated: 2019-05-20
    const ISO_639_1_CODES = [
        'aa',
        'ab',
        'ae',
        'af',
        'ak',
        'am',
        'an',
        'ar',
        'as',
        'av',
        'ay',
        'az',
        'ba',
        'be',
        'bg',
        'bh',
        'bi',
        'bm',
        'bn',
        'bo',
        'br',
        'bs',
        'ca',
        'ce',
        'ch',
        'co',
        'cr',
        'cs',
        'cu',
        'cv',
        'cy',
        'da',
        'de',
        'dv',
        'dz',
        'ee',
        'el',
        'en',
        'eo',
        'es',
        'et',
        'eu',
        'fa',
        'ff',
        'fi',
        'fj',
        'fo',
        'fr',
        'fy',
        'ga',
        'gd',
        'gl',
        'gn',
        'gu',
        'gv',
        'ha',
        'he',
        'hi',
        'ho',
        'hr',
        'ht',
        'hu',
        'hy',
        'hz',
        'ia',
        'id',
        'ie',
        'ig',
        'ii',
        'ik',
        'io',
        'is',
        'it',
        'iu',
        'ja',
        'jv',
        'ka',
        'kg',
        'ki',
        'kj',
        'kk',
        'kl',
        'km',
        'kn',
        'ko',
        'kr',
        'ks',
        'ku',
        'kv',
        'kw',
        'ky',
        'la',
        'lb',
        'lg',
        'li',
        'ln',
        'lo',
        'lt',
        'lu',
        'lv',
        'mg',
        'mh',
        'mi',
        'mk',
        'ml',
        'mn',
        'mr',
        'ms',
        'mt',
        'my',
        'na',
        'nb',
        'nd',
        'ne',
        'ng',
        'nl',
        'nn',
        'no',
        'nr',
        'nv',
        'ny',
        'oc',
        'oj',
        'om',
        'or',
        'os',
        'pa',
        'pi',
        'pl',
        'ps',
        'pt',
        'qu',
        'rm',
        'rn',
        'ro',
        'ru',
        'rw',
        'sa',
        'sc',
        'sd',
        'se',
        'sg',
        'si',
        'sk',
        'sl',
        'sm',
        'sn',
        'so',
        'sq',
        'sr',
        'ss',
        'st',
        'su',
        'sv',
        'sw',
        'ta',
        'te',
        'tg',
        'th',
        'ti',
        'tk',
        'tl',
        'tn',
        'to',
        'tr',
        'ts',
        'tt',
        'tw',
        'ty',
        'ug',
        'uk',
        'ur',
        'uz',
        've',
        'vi',
        'vo',
        'wa',
        'wo',
        'xh',
        'yi',
        'yo',
        'za',
        'zh',
        'zu',
    ];

    const LOCALE_TO_LANGUAGE = [
        'au'    => 'en-AU',
        'en-au' => 'en-AU',
        'en-us' => 'en',
        'mx'    => 'es',
        'pt-pt' => 'pt-PT',
        'br'    => 'pt-BR',
        'vi'    => 'vi',
        'no'    => 'nn',
        'nn'    => 'nn',
    ];

    const COUNTRY_TO_LOCALE = [
        'AU' => 'en-au',
        'US' => 'en-us',
        'PT' => 'pt-pt',
        'BR' => 'pt-br',
        'DE' => 'de',
        'ES' => 'es',
        'MX' => 'es',
        'VN' => 'vi',
        'NO' => 'no',
    ];

    public static function codes(): array
    {
        return array_keys(static::ALL);
    }

    public static function getLanguageCode($locale, $default = 'en')
    {
        return self::LOCALE_TO_LANGUAGE[$locale] ?? $default;
    }
}
