# TODO: Work in progress.
services:
  html:
    factory: go1\util\Text::defaultPurifier
  access_checker:
    class: go1\util\AccessChecker
  portal_checker:
    class: go1\util\portal\PortalChecker
  lo_checker:
    class: go1\util\lo\LoChecker
  go1.client.accounts:
    class: go1\clients\AccountsClient
    arguments: [@db.go1, @cache, %accounts_name%]
  go1.client.queue:
    class: go1\clients\QueueClient
    arguments: [@client, %queue_url%]

  # TODO
  # =====================
  # go1.client.currency
  # go1.client.download-pdf
  # go1.client.eck
  # go1.client.entity
  # go1.client.es
  # go1.client.firebase
  # go1.client.go1s3
  # go1.client.graph
  # go1.client.graphin
  # go1.client.lo
  # go1.client.mail
  # go1.client.mq
  # go1.client.notification
  # go1.client.payment
  # go1.client.portal
  # go1.client.realtime
  # go1.client.rules
  # go1.client.s3
  # go1.client.sms
  # go1.client.user
